M48
; DRILL file KiCad 10.0.1 date 2026-05-22T19:31:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-22T19:31:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X25.169Y-17.842
X25.852Y-144.65
X58.202Y-144.5
X58.926Y-17.893
M30
